"use client";
import React from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";

const AboutMeComponent = () => {
  const handleWhatsAppClick = () => {
    const phoneNumber = "917660915810"; // Replace with your WhatsApp number (without +)
    const message = "Hello Anji, I am interested in hiring you!";
    const encodedMessage = encodeURIComponent(message);
    const whatsappURL = `https://wa.me/${phoneNumber}?text=${encodedMessage}`;

    window.open(whatsappURL, "_blank");
  };
  return (
    <div className="bg-gray-900 pt-20 text-white">
      <Head>
        <title>Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="container mx-auto px-6">
        <div className="bg-gray-900 text-white p-8 rounded-lg shadow-lg">
          <div className="flex flex-col md:flex-row items-center md:items-start gap-12">
            {/* Profile Image Container */}
            <div className="relative w-3/4 md:w-1/3 lg:w-1/4 mx-auto md:mx-0">
              <div className="relative z-10">
                <Image
                  src="/image/profile.jpg"
                  alt="Profile Image"
                  width={250}
                  height={250}
                  className="rounded-lg object-cover w-full"
                />
              </div>
              <div className="absolute top-4 left-4 w-full h-full border-8 border-blue-500 z-0 rounded-lg m-2"></div>
            </div>

            {/* About Me Text Container */}
            <div className="w-full md:w-2/3 text-center md:text-left">
              <h2 className="text-3xl font-bold mb-4">About Me</h2>
              <p className="text-lg mb-6 leading-relaxed">
                I am a React.js Developer with 4.10+ years of IT experience,
                including 3.6+ years of expertise in React.js and 6 months in
                Node.js, MongoDB, and Vue.js. I specialize in building scalable,
                high-performance web applications using React.js, Redux,
                Next.js, TypeScript, and Tailwind CSS, ensuring modern UI/UX
                experiences. With a strong full-stack background, I have
                hands-on experience in Node.js, Express.js, and MongoDB,
                enabling seamless frontend-backend integration. I am proficient
                in RESTful API development, server-side rendering (SSR), and
                state management with Redux Toolkit, optimizing application
                efficiency. I have worked on AI-driven platforms, e-commerce
                solutions, brand compliance tools, and project management
                systems, delivering user-friendly, responsive applications. My
                expertise in Vite, Webpack, and Agile methodologies ensures
                smooth project execution. Passionate about clean code,
                performance optimization, and best practices, I constantly
                explore the latest technologies to enhance my skills.
              </p>

              {/* Buttons */}
              <div className="flex flex-col sm:flex-row gap-4">
                <button
                  className="bg-buttonColorMain hover:bg-blue-700 w-1/2 h-20 text-white font-extrabold py-2 px-4 rounded"
                  onClick={handleWhatsAppClick}
                >
                  HIRE ME
                </button>
                <a
                  href="/anji-resume.pdf"
                  download="Anji_Resume.pdf"
                  className="bg-gray-900 border-buttonBorderColor border-2 hover:bg-gray-700 w-1/2 h-20 text-white font-extrabold py-2 px-4 rounded justify-center items-center transition duration-300 shadow-md flex"
                >
                  RESUME
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default AboutMeComponent;
