import React from "react";
import Sidebar from "./ExperienceComponent";
import ProgressWidget from "./AboutMeComponent";
import CardioWidget from "./PortfolioComponent";
import ProgressTracking from "./timeLine";
import styles from "./Sidebar.module.css";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import AboutMeComponent from "./AboutMeComponent";
import PortfolioComponent from "./PortfolioComponent";
import ContactComponent from "./contactComponent";
import ExperienceComponent from "./ExperienceComponent";
import Timeline from "./timeLine";

const DashboardComponent = () => {
  return (
    <div className="bg-gray-900 text-white min-h-screen w-full flex md:block">
      {/* <Head>
        <title>Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head> */}

      <main className="container-max">
        <div className="text-center flex flex-col items-start font-serif">
          <h1 className="text-5xl text-gray-500 font-extrabold mb-4 pl-20 font-serif mt-14">
            I'm a
          </h1>
          <h2 className="text-8xl font-extrabold mb-8">
            <span className="pl-9">Full Stack</span>
            <br />
            <span>Software</span>
            <br />
            <span className="pl-20"> Developer</span>
            <span className="w-3 h-3 inline-block bg-white"></span>
          </h2>
        </div>
        <div className="ml-20 mt-4">
          <button className="bg-buttonColorMain w-1/4 h-20 hover:bg-blue-700 text-white font-extrabold py-2 px-4 rounded">
            Previous Projects
          </button>
        </div>
        <AboutMeComponent />
        <ExperienceComponent />
        <PortfolioComponent />
        <Timeline />
        <ContactComponent />
      </main>
    </div>
  );
};

export default DashboardComponent;
