import React from "react";
import Head from "next/head";
import ProjectCard from "@/components/ProjectCard";
import Timeline from "./timeLine";

const projects = [
  {
    title: "Banking System",
    description:
      "A banking system designed for seamless transactions and account management. It includes features such as secure authentication, fund transfers. The platform is currently experiencing performance issues, mainly due to slow content loading on the server.",
    technologies: ["MERN STACK", "Bootstrap"],
    videoURL: "/videos/bank-c8cc8943.mp4",
    livePreviewUrl: "https://onlinemybank.netlify.app",
    viewCodeUrl: null,
  },
  {
    title: "Blog App",
    description:
      "A blogging platform where users can create, edit, and delete posts easily. It allows users to share their blogs with others and explore content from different authors. The system is built with an intuitive UI for seamless navigation and user engagement.",
    technologies: ["React", "Node.js", "Express", "MIUI"],
    videoURL: "/videos/blog-af07fe4b.mp4",
    livePreviewUrl: "https://iblogz.netlify.app/",
    viewCodeUrl: null,
  },
];

const educationData = [
  {
    degree: "Bachelor's Degree",
    years: "2016 - 2020",
    institution: "Suresh Gyan Vihar University, Jaipur",
    side: "left",
  },
];

const PortfolioComponent = () => {
  return (
    <div className="bg-gray-900 text-white ">
      <Head>
        <title>Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="container mx-auto px-4 py-16">
        {/* Projects Section */}
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold">Projects</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 place-items-center md:place-items-stretch">
          {projects.map((project, index) => (
            <ProjectCard
              key={index}
              title={project.title}
              description={project.description}
              technologies={project.technologies}
              videoURL={project.videoURL}
              livePreviewUrl={project.livePreviewUrl}
              viewCodeUrl={project.viewCodeUrl}
            />
          ))}
        </div>
      </main>
    </div>
  );
};

export default PortfolioComponent;
